### ISSUE TITLE
SegFault on running SimAnneal with aggregates

### ISSUE THREAD

**Issue by retallickj** [siqad/siqad#69] opened 2020-08-31 15:15 UTC
Cannot call SimAnneal on designs containing aggregates. Log file gives a very useful "Fatal Error".

**Comment by samuelngsh** [comment] 2020-08-31 21:40
This is due to a bug with loading aggregates, the problem is observed both when loading aggregates from save files and from simulation results.

Fixed in commit 2cea47a4769bd80dc31ba5673bfe74153c79be6b

**Closed by samuelngsh** 2020-08-31 21:40 UTC
