### ISSUE TITLE
SegFault when closing tool after loading and performing an undo-able task.

### ISSUE THREAD

**Issue by NathanChiu** [siqad/siqad#38] opened 2018-08-14 18:20 UTC
**Environment**
Ubuntu 18.04
**Steps to reproduce**
1. Load a .sqd file containing at least 1 moveable item.
2. Move/delete/c&p the item.
3. Close the tool.
**Expected Result**
Exits without error.
**Actual Result**
Segfaults on exit.
**Visual Proof**
gdb provides this:
`Thread 1 "siqad" received signal SIGSEGV, Segmentation fault.
0x00007ffff6682290 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff6682290 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff66827f6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff662c1b4 in QFileInfo::QFileInfo(QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00005555555c9b61 in gui::ApplicationGUI::updateWindowTitle() (this=0x7fffffffdd10) at src/gui/application.cc:606
#4  0x00005555555d69de in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (gui::ApplicationGUI::*)()>::call(void (gui::ApplicationGUI::*)()
, gui::ApplicationGUI*, void**) (f=(void (gui::ApplicationGUI::*)(gui::ApplicationGUI * const)) 0x5555555c9af8 <gui::ApplicationGUI::updateWindowTitle()>, o=0x7fffffffdd1
0, arg=0x7fffffffd7b0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:136
#5  0x00005555555d5900 in QtPrivate::FunctionPointer<void (gui::ApplicationGUI::*)()>::call<QtPrivate::List<>, void>(void (gui::ApplicationGUI::*)(), gui::ApplicationGUI*
, void**) (f=(void (gui::ApplicationGUI::*)(gui::ApplicationGUI * const)) 0x5555555c9af8 <gui::ApplicationGUI::updateWindowTitle()>, o=0x7fffffffdd10, arg=0x7fffffffd7b0)
 at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:169
#6  0x00005555555d49a1 in QtPrivate::QSlotObject<void (gui::ApplicationGUI::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*
) (which=1, this_=0x555555f2efe0, r=0x7fffffffdd10, a=0x7fffffffd7b0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:120
#7  0x00007ffff673e6cf in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x000055555561fe25 in gui::DesignPanel::sig_undoStackCleanChanged(bool) (this=0x555555c1c4f0, _t1=true) at build/debug/.moc/moc_design_panel.cpp:410
#9  0x0000555555620107 in gui::DesignPanel::emitUndoStackCleanChanged(bool) (this=0x555555c1c4f0, c=true) at build/debug/.moc/../../../src/gui/widgets/design_panel.h:209
#10 0x000055555561f492 in gui::DesignPanel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555555c1c4f0, _c=QMetaObject::InvokeMetaMethod, _id=20, _a=
0x7fffffffda00) at build/debug/.moc/moc_design_panel.cpp:217
#11 0x00007ffff673e5b5 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff77f0602 in QUndoStack::cleanChanged(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff77f1891 in QUndoStack::clear() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff77f18d2 in QUndoStack::~QUndoStack() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff77f18e9 in QUndoStack::~QUndoStack() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5`

Will revisit later, since the error doesn't affect tool performance.

**Comment by samuelngsh** [comment] 2020-05-19 07:33
I know it's been some time and much has changed in the code base. I can't reproduce this issue and it might very well have been fixed long ago. @NathanChiu is this still relevant?

**Comment by samuelngsh** [comment] 2020-05-23 23:49
Closing unless the problem returns.

**Closed by samuelngsh** 2020-05-23 23:49 UTC
Labels: bug
